# Generated by Django 3.2.8 on 2021-11-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_rename_guitar_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
    ]
