# Generated by Django 3.2.8 on 2021-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='proyectos', verbose_name='Imagen'),
        ),
    ]
