# Generated by Django 3.2.8 on 2021-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='webside',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='proyectos', verbose_name='Imagen'),
        ),
    ]
