# Generated by Django 3.2.8 on 2021-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyecto_image'),
        ('proyectos', '0004_auto_20211116_2151'),
    ]

    operations = [
    ]
