# Generated by Django 3.2.8 on 2021-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(upload_to='recetas', verbose_name='Imagen'),
        ),
    ]
